dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libunwind-dev
      env: MYCC=gcc-4.9 MYCXX=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libunwind-dev
      env: MYCC=gcc-5 MYCXX=g++-5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libunwind-dev
      env: MYCC=gcc-6 MYCXX=g++-6
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libunwind-dev
            - lcov
      env: MYCC=gcc-6 MYCXX=g++-6 CODE_COVERAGE=on
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - clang-3.8
            - libunwind-dev
      env: MYCC=clang-3.8 MYCXX=clang++-3.8
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - libunwind-dev
      env: MYCC=clang-3.9 MYCXX=clang++-3.9
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libunwind-dev
      env: MYCC=clang-4.0 MYCXX=clang++-4.0
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libunwind-dev
      env: MYCC=clang-5.0 MYCXX=clang++-5.0
    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-mingw-w64-x86-64
            - libunwind-dev
      env: MYCC=/usr/bin/x86_64-w64-mingw32-gcc MYCXX=/usr/bin/x86_64-w64-mingw32-g++

script:
  - mkdir build
  - cd build
  - BUILD_TYPE=Release
  - |
    if [[ "$MYCC" == *mingw* ]] ; then
      ADD_OPTS="-DCMAKE_TOOLCHAIN_FILE=$TRAVIS_BUILD_DIR/Toolchain-cross-mingw-linux.cmake"
    else
      ADD_OPTS="-DCMAKE_C_COMPILER=$MYCC -DCMAKE_CXX_COMPILER=$MYCXX"
    fi
  - |
    if [[ -n "$ENABLE_ASAN" ]] ; then
      ADD_OPTS="$ADD_OPTS -DENABLE_ASAN=$ENABLE_ASAN"
      BUILD_TYPE=Debug
    fi
  - |
    if [[ -n "$ENABLE_UBSAN" ]] ; then
      ADD_OPTS="$ADD_OPTS -DENABLE_UBSAN=$ENABLE_UBSAN"
      BUILD_TYPE=Debug
    fi
  - |
    if [[ -n "$CODE_COVERAGE" ]] ; then
      ADD_OPTS="$ADD_OPTS -DENABLE_COVERAGE=$CODE_COVERAGE"
      BUILD_TYPE=Debug
    fi
  - ADD_OPTS="$ADD_OPTS -DCMAKE_BUILD_TYPE=$BUILD_TYPE"
  - cmake $ADD_OPTS ..
  - make
  - if [[ "$MYCC" != *mingw* ]] ; then make runtest; fi
  - |
    if [[ -n "$CODE_COVERAGE" ]] ; then
      lcov -d . -c -o coverage.info                      # parse coverage data
      lcov -r coverage.info "/usr*" -o coverage.info     # remove data for system headers
      lcov -l coverage.info                              # just list a short summary of the results
      bash <(curl -s https://codecov.io/bash)
    fi
