dist: xenial
language: cpp

matrix:
  include:
    - compiler: gcc-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - libunwind8-dev
      env: MYCC=gcc-4.8 MYCXX=g++-4.8
    - compiler: gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libunwind8-dev
      env: MYCC=gcc-5 MYCXX=g++-5
    - compiler: gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libunwind8-dev
      env: MYCC=gcc-6 MYCXX=g++-6
    - compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libunwind8-dev
      env: MYCC=gcc-7 MYCXX=g++-7
    - compiler: gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - libunwind8-dev
      env: MYCC=gcc-8 MYCXX=g++-8
    - compiler: gcc-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libunwind8-dev
      env: MYCC=gcc-9 MYCXX=g++-9
    - compiler: gcc-10
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - libunwind8-dev
      env: MYCC=gcc-10 MYCXX=g++-10
    - compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libunwind8-dev
            - lcov
      env: MYCC=gcc-7 MYCXX=g++-7 CODE_COVERAGE=on
    - compiler: clang-3.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - clang-3.8
            - libunwind8-dev
      env: MYCC=clang-3.8 MYCXX=clang++-3.8
    - compiler: clang-3.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - libunwind8-dev
      env: MYCC=clang-3.9 MYCXX=clang++-3.9
    - compiler: clang-4.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial
          packages:
            - clang-4.0
            - libunwind8-dev
      env: MYCC=clang-4.0 MYCXX=clang++-4.0
    - compiler: clang-5.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial
          packages:
            - clang-5.0
            - libunwind8-dev
      env: MYCC=clang-5.0 MYCXX=clang++-5.0
    - compiler: clang-6.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
            - libunwind8-dev
      env: MYCC=clang-6.0 MYCXX=clang++-6.0
    - compiler: clang-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
            - libunwind8-dev
      env: MYCC=clang MYCXX=clang++
    - compiler: clang-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
            - libunwind8-dev
      env: MYCC=clang MYCXX=clang++
    - compiler: clang-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main
              key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages:
            - clang-9
            - libunwind8-dev
      env: MYCC=clang-9 MYCXX=clang++-9
    - compiler: clang-10
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main
              key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages:
            - clang-10
            - libunwind8-dev
      env: MYCC=clang-10 MYCXX=clang++-10
    - compiler: clang-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
            - libunwind8-dev
      env: MYCC=clang MYCXX=clang++ ENABLE_UBSAN=on
    - compiler: gcc-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libunwind8-dev
      env: MYCC=gcc-9 MYCXX=g++-9 ENABLE_ASAN=on
    - compiler: gcc-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libunwind8-dev
      env: MYCC=gcc-9 MYCXX=g++-9 ENABLE_TSAN=on
    - compiler: x86_64-w64-mingw32-g++
      addons:
        apt:
          packages:
            - g++-mingw-w64-x86-64
            - libunwind8-dev
      env: MYCC=/usr/bin/x86_64-w64-mingw32-gcc MYCXX=/usr/bin/x86_64-w64-mingw32-g++

script:
  - mkdir build
  - cd build
  - BUILD_TYPE=Release
  - |
    if [[ "$MYCC" == *mingw* ]] ; then
      ADD_OPTS="-DCMAKE_TOOLCHAIN_FILE=$TRAVIS_BUILD_DIR/Toolchain-cross-mingw-linux.cmake"
    else
      ADD_OPTS="-DCMAKE_C_COMPILER=$MYCC -DCMAKE_CXX_COMPILER=$MYCXX"
    fi
  - |
    if [[ -n "$ENABLE_ASAN" ]] ; then
      ADD_OPTS="$ADD_OPTS -DENABLE_ASAN=$ENABLE_ASAN"
      BUILD_TYPE=Debug
    fi
  - |
    if [[ -n "$ENABLE_TSAN" ]] ; then
      ADD_OPTS="$ADD_OPTS -DENABLE_TSAN=$ENABLE_TSAN"
      BUILD_TYPE=Debug
    fi
  - |
    if [[ -n "$ENABLE_UBSAN" ]] ; then
      ADD_OPTS="$ADD_OPTS -DENABLE_UBSAN=$ENABLE_UBSAN"
      BUILD_TYPE=Debug
    fi
  - |
    if [[ -n "$CODE_COVERAGE" ]] ; then
      ADD_OPTS="$ADD_OPTS -DENABLE_COVERAGE=$CODE_COVERAGE"
      BUILD_TYPE=Debug
    fi
  - ADD_OPTS="$ADD_OPTS -DCMAKE_BUILD_TYPE=$BUILD_TYPE"
  - cmake $ADD_OPTS ..
  - make
  - if [[ "$MYCC" != *mingw* ]] ; then make runtest; fi
  - |
    if [[ -n "$CODE_COVERAGE" ]] ; then
      lcov -d . -c -o coverage.info                      # parse coverage data
      lcov -r coverage.info "/usr*" -o coverage.info     # remove data for system headers
      lcov -l coverage.info                              # just list a short summary of the results
      bash <(curl -s https://codecov.io/bash)
    fi
