# Windows Build Configuration for AppVeyor

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

environment:
  matrix:
    - arch: x64
      configuration: Release

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

build_script:
  - md build
  - cd build
  - cmake .. -A %arch%
  - cmake --build . --config %configuration%

test_script:
  - ctest -VV
