# Windows Build Configuration for AppVeyor

image:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - arch: Win64
      configuration: Release

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

build_script:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017 %arch%" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015 %arch%" )
  - md build
  - cd build
  - cmake .. -G %generator%
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest -VV
