# Windows Build Configuration for AppVeyor

image:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - x64

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

build_script:
  - set buildcfg=Release
  - md build
  - cd build
  - cmake ..
  - cmake --build . --config %buildcfg%

test_script:
  - ctest -VV
